Amanda797/Mythology-Mayhem

Mythology Mayhem/Assets/Animations/GreekBoy/Greek-Boy-Sword-Attack.anim, Mythology Mayhem/Assets/PlayerStats.cs, Mythology Mayhem/Assets/Prefabs/GreekBoy.prefab, Mythology Mayhem/Assets/Prefabs/MouseEnemy.prefab, Mythology Mayhem/Assets/Scenes/Library of Alexandria.unity, Mythology Mayhem/Assets/Scripts/2D/MouseAI.cs, Mythology Mayhem/ProjectSettings/TagManager.asset
I had to move the player down some due the fact the player's attack animation sword arc wouldn't be able to hit the mouse
=> Made the player hit the mouse

Mythology Mayhem/Assets/Greek/Library of Alexandria/frontfacingladderbold.png, Mythology Mayhem/Assets/Greek/Library of Alexandria/frontfacingladderbold.png.meta, Mythology Mayhem/Assets/Greek/Library of Alexandria/pedestaldarker.png, Mythology Mayhem/Assets/Greek/Library of Alexandria/pedestaldarker.png.meta, Mythology Mayhem/Assets/Greek/MenuHud.meta, Mythology Mayhem/Assets/Greek/MenuHud/Aztecbutton.png, Mythology Mayhem/Assets/Greek/MenuHud/Aztecbutton.png.meta, Mythology Mayhem/Assets/Greek/MenuHud/celticbutton.png, Mythology Mayhem/Assets/Greek/MenuHud/celticbutton.png.meta, Mythology Mayhem/Assets/Greek/MenuHud/egyptbutton.png, Mythology Mayhem/Assets/Greek/MenuHud/egyptbutton.png.meta, Mythology Mayhem/Assets/Greek/MenuHud/greek button.png, Mythology Mayhem/Assets/Greek/MenuHud/greek button.png.meta, Mythology Mayhem/Assets/Scenes/Library 3D 2.unity, Mythology Mayhem/Assets/Scenes/Library of Alexandria.unity, Mythology Mayhem/UserSettings/EditorUserSettings.asset
=> changes to 2D library

Mythology Mayhem/Assets/Greek/Library of Alexandria/archeswithhall.png.meta, Mythology Mayhem/Assets/Greek/Library of Alexandria/bg.png.meta, Mythology Mayhem/Assets/Greek/Library of Alexandria/bigscrollcase.png.meta, Mythology Mayhem/Assets/Greek/Library of Alexandria/ceiling.png.meta, Mythology Mayhem/Assets/Greek/Library of Alexandria/column.png.meta, Mythology Mayhem/Assets/Greek/Library of Alexandria/scrollcaseHalfWide.png.meta, Mythology Mayhem/Assets/Scenes/2D Scenes/Library of Alexandria.unity, Mythology Mayhem/UserSettings/EditorUserSettings.asset
Organized the 2D Library of Alexandria scene:
Organized all of the rendering layers
Deleted redundant assets
Turned several assets into tiled sprites
Made a few assets full rects with custom tile outlines
=> Updates to 2D Librray of Alexandria Scene

Mythology Mayhem/Assets/Scenes/2D Scenes/Library of Alexandria.unity, Mythology Mayhem/UserSettings/EditorUserSettings.asset
Greek Music is attached to Directional Light game object.
=> Fixed Z Values of Chairs and Tables, Added Greek Music to 2D LoA

Mythology Mayhem/Assets/Prefabs/Amunet_Player.prefab, Mythology Mayhem/Assets/Prefabs/Mico-Inca.prefab, Mythology Mayhem/Assets/Prefabs/Norm-Norse.prefab, Mythology Mayhem/Assets/Scenes/Menus/CharacterSelection.unity, Mythology Mayhem/Assets/Scenes/Menus/MainMenu.unity, Mythology Mayhem/Assets/Scripts/CharacterSelectDetails.cs, Mythology Mayhem/Assets/Scripts/UI/Menus/MenuManager.cs, Mythology Mayhem/Assets/Scripts/playerSpwaner.cs, Mythology Mayhem/Assets/_SceneData/MainMenu.json, Mythology Mayhem/Assets/_SceneData/MainMenu.json.meta, Mythology Mayhem/Assets/_Selectables/2D.asset, Mythology Mayhem/UserSettings/EditorUserSettings.asset
Base functionality is in; will commit design/aesthetic changes later
=> Character Selection Screen Complete

Mythology Mayhem/Assets/Scenes/2D Scenes/2Dlabyrinth_Levers 1.unity
attached anim controler to all levers
=> Samantha durfee

Mythology Mayhem/Assets/Animations/Owl_Follower.meta, Mythology Mayhem/Assets/Animations/Owl_Follower/Owl_Controller.controller, Mythology Mayhem/Assets/Animations/Owl_Follower/Owl_Controller.controller.meta, Mythology Mayhem/Assets/Animations/Owl_Follower/Owl_Idle.anim, Mythology Mayhem/Assets/Animations/Owl_Follower/Owl_Idle.anim.meta, Mythology Mayhem/Assets/Scenes/Tests/Hixon_Test_Scene.unity, Mythology Mayhem/Assets/Scripts/2D/Owl_Animator.cs, Mythology Mayhem/Assets/Scripts/2D/Owl_Animator.cs.meta, Mythology Mayhem/Assets/Scripts/2D/Owl_Attack.cs, Mythology Mayhem/Assets/Scripts/2D/Owl_Attack.cs.meta, Mythology Mayhem/Assets/Scripts/2D/PlayerStats.cs, Mythology Mayhem/Assets/Scripts/2D/owlPoint.cs, Mythology Mayhem/Assets/Scripts/2D/owlPoint.cs.meta
Adding in what I have on the owl. It only works in my personal 2D scene with Amunet at the moment. Reasoning? She was what I had active as I had just finished animating her shoot down animation. The modification to Player stats was to set a point for the owl to fly to that flipped with the player. Having all 2D players potentially having the owl location means you could come up with flying companions for the others. Like a falcon or hawk for Amunet or a Raven for Gorm. As for Micos I don't really know any birds that were sacred to the Incan people.
=> pushing a basic version of the owl.

Mythology Mayhem/Assets/3D Assets/Greek/Enemies/Medusa/Animations/Medusa_Anim_Controller.controller, Mythology Mayhem/Assets/Global Assets/Art/VFX/M_Glare.mat, Mythology Mayhem/Assets/Global Assets/Art/VFX/M_Glare.mat.meta, Mythology Mayhem/Assets/Global Assets/Art/VFX/S_Glare.shadergraph, Mythology Mayhem/Assets/Global Assets/Art/VFX/S_Glare.shadergraph.meta, Mythology Mayhem/Assets/Global Assets/Art/VFX/T_Glare.png, Mythology Mayhem/Assets/Global Assets/Art/VFX/T_Glare.png.meta, Mythology Mayhem/Assets/Global Assets/Art/VFX/T_Gradient.png, Mythology Mayhem/Assets/Global Assets/Art/VFX/T_Gradient.png.meta, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/3DMedusaCave.unity
Replaced madusa beam with M_Glare
=> Glare VFX added

Mythology Mayhem/Assets/2D Assets/Global/Scripts/2D/TwoDLever.cs, Mythology Mayhem/Assets/3D Assets/Global/Scripts/ThreeDLever.cs, Mythology Mayhem/Assets/3D Assets/Global/Scroll3D.prefab, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/GreekLibrary_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekLibrary_3D.unity, Mythology Mayhem/Assets/Global Assets/Scripts/DoorCode.cs, Mythology Mayhem/Assets/Global Assets/Scripts/ScrollPopup.cs, Mythology Mayhem/Assets/Global Assets/Scripts/ScrollScript.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/GameManager.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/SceneTransitionPoint.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/SceneTransitionPoint2D.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/SceneTransitionPoint3D.cs
I updated the TwoDLever, ThreeDLever, ScrollPopup(3d scrolls), ScrollScript(2d scrolls), SceneTransitionPoint2D and SceneTransitionPoint3D so that they do not run every frame. Now they start on trigger enter and end on trigger exit. They only check for player input while the player is within the trigger.
=> Interactables

Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D.unity, Mythology Mayhem/Assets/Global Assets/Scripts/QuizManager.cs
The Medusa fight now loads once the quiz has completed.
=> Fates Quiz

Mythology Mayhem/Assets/Global Assets/Scripts/HealthUIController.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/GameManager.cs
Fixed a bug where the players health ui would disappear after transitioning between loaded scenes.
=> Player Health UI

Mythology Mayhem/Assets/2D Assets/Global/Scripts/2D/CavernLeverPuzzleManager.cs, Mythology Mayhem/Assets/2D Assets/Greek/2Dpuzzle/LeverPuzzle.cs, Mythology Mayhem/Assets/2D Assets/Greek/2Dpuzzle/LeverPuzzleManager.cs, Mythology Mayhem/Assets/Global Assets/Prefabs/OwlFollower.prefab, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D_Levers.unity, Mythology Mayhem/Assets/Global Assets/Scripts/Companions/Companion.cs, Mythology Mayhem/Assets/Global Assets/Scripts/Companions/CompanionController.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/LocalGameManager.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/SaveData.cs
The player can now enter the Greek Cavern 2D Lever Puzzle. The player can now activate the levers in the following sequence (on, off, on, off ...) Once activated properly the owl is obtained and saved to json. The owl will appear on all players that have this companion after this point and will the follow the player.
=> Greek Cavern 2D Lever Puzzle and Owl Companion

Mythology Mayhem/Assets/3D Assets/Global/Scripts/WeaponSwitcher.cs, Mythology Mayhem/Assets/3D Assets/Greek/Enemies/Medusa/Scripts/MedusaControlScript.cs, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekLabyrinth_3D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekMedusa_3D.unity
Fixed the mirror displaying on load in some instances. Fixed the bow being displayed if the player has not yet obtained it. Fixed the door not appearing after defeating medusa. Added a collider in the 3D Greek Labyrinth scene preventing the player from climbing the stairs at the end and falling out of the map.
=> Weapon Switcher

Mythology Mayhem/Assets/2D Assets/Global/Scripts/2D/PlayerStats.cs, Mythology Mayhem/Assets/2D Assets/Greek/2DCave/cavepathway.png.meta, Mythology Mayhem/Assets/2D Assets/Greek/2Dpuzzle/StatueBody2D.cs, Mythology Mayhem/Assets/2D Assets/Greek/2Dpuzzle/StatueBody3D.cs, Mythology Mayhem/Assets/2D Assets/Greek/2Dpuzzle/StatuePuzzle.cs, Mythology Mayhem/Assets/2D Assets/Greek/2Dpuzzle/StatueWeapon.cs, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D_Statues.unity, Mythology Mayhem/Assets/Global Assets/Scripts/NewHeartPickup.cs, Mythology Mayhem/ProjectSettings/TagManager.asset
The player can now complete the Greek Cavern Statue Puzzle by placing each weapon on the correct statues. When a the player picks up a heart their max health now properly increases.
=> Greek Cavern Statue Puzzle & Heart Pickups

Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D_Levers.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D_Statues.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/GreekLibrary_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Labyrinth_Scenes/GreekLabyrinth_2D_Levers.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Labyrinth_Scenes/GreekLabyrinth_2D_Pedastals.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Norse/Viking2D enemie test scene.unity, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekCavern_3D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekLabyrinth_3D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/Menus/MainMenu.unity, Mythology Mayhem/Assets/Global Assets/Scripts/DoorCode.cs, Mythology Mayhem/Assets/Global Assets/Scripts/QuizManager.cs, Mythology Mayhem/Assets/Global Assets/Scripts/QuizTrigger.cs, Mythology Mayhem/Assets/Global Assets/Scripts/SaveScene.cs, Mythology Mayhem/Assets/Global Assets/Scripts/ScrollScript.cs, Mythology Mayhem/Assets/Global Assets/Scripts/UI/UI/Menus/MenuManager.cs
Fixed a NullReferenceException with the DoorCode script. Disabled the scene saving feature as it was only saving the first scene. Fixed the mirror check with the fates quiz.
The game now pauses when the player interacts with the fates or a scroll.
=> Build Bug Fixes

Mythology Mayhem/Assets/2D Assets/Global/Scripts/2D/PlayerStats.cs, Mythology Mayhem/Assets/2D Assets/Greek/FountainScript.cs, Mythology Mayhem/Assets/3D Assets/Global/Player 3D/Tobias_3D.prefab, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/GreekLibrary_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Norse/VikingVillage_2D.unity, Mythology Mayhem/Assets/Global Assets/Scripts/FPSHealth.cs, Mythology Mayhem/Assets/Global Assets/Scripts/HealingPotion.cs, Mythology Mayhem/Assets/Global Assets/Scripts/HealthUIController.cs, Mythology Mayhem/Assets/Global Assets/Scripts/PlayerHeartState.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/GameData.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/GameManager.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/SaveData.cs
The player health UI now updates properly on respawn. The Health potions in the 2D Viking Village can now be seen by the player. Collecting a new heart now increases max health and current health. 3D health potions now play a sfx.
=> Player Health

Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Norse/VikingMine_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Norse/VikingVillage_3D.unity
3D Viking Village mini game UI no longer displays in the 2D Viking Village Level. The player can now enter the 3D Viking Village and the 2D Viking Mine.
=> Viking Village & Mine

Mythology Mayhem/Assets/Global Assets/Art/birdstatue.png, Mythology Mayhem/Assets/Global Assets/Art/birdstatue.png.meta, Mythology Mayhem/Assets/Global Assets/Art/statuebird.fbx, Mythology Mayhem/Assets/Global Assets/Art/statuebird.fbx.meta, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Labyrinth_Scenes/GreekLabyrinth_2D_Pedastals.unity, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekLabyrinth_3D.unity
Added a bird sprite and a bird fbx for the 2D and 3D air element.
=> Air Element

Mythology Mayhem/Assets/2D Assets/Global/Scripts/2D/PlayerStats.cs, Mythology Mayhem/Assets/2D Assets/Greek/FountainScript.cs, Mythology Mayhem/Assets/Global Assets/Scripts/FPSHealth.cs, Mythology Mayhem/Assets/Global Assets/Scripts/HealingPotion.cs, Mythology Mayhem/Assets/Global Assets/Scripts/HealthUIController.cs, Mythology Mayhem/Assets/Global Assets/Scripts/PlayerHeartState.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/GameManager.cs
Fixed a bug that would heal the player when they entered a new scene.
=> Health System

Mythology Mayhem/Assets/2D Assets/Global/Scripts/2D/CavernLeverPuzzleManager.cs, Mythology Mayhem/Assets/2D Assets/Global/Scripts/2D/PlayerStats.cs, Mythology Mayhem/Assets/2D Assets/Global/Scripts/2D/TwoDBow.cs, Mythology Mayhem/Assets/2D Assets/Global/Scripts/2D/TwoDMirror.cs, Mythology Mayhem/Assets/2D Assets/Greek/2Dpuzzle/LeverPuzzleManager.cs, Mythology Mayhem/Assets/3D Assets/Global/Scripts/WeaponSwitcher.cs, Mythology Mayhem/Assets/Global Assets/Scripts/Companions/CompanionController.cs, Mythology Mayhem/Assets/Global Assets/Scripts/FPSHealth.cs, Mythology Mayhem/Assets/Global Assets/Scripts/HealthUIController.cs, Mythology Mayhem/Assets/Global Assets/Scripts/QuizManager.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/GameData.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/SaveData.cs
All player data is now set tom the game data file first then the save data is saved. Updated the fate quiz to pause after the cursor is set.
=> Fate Quiz & Save System

Mythology Mayhem/Assets/Global Assets/Scenes/Menus/MainMenu.unity
The Press X to do X now has a background image.
=> Interact Background Image

Mythology Mayhem/Assets/2D Assets/Greek/FountainScript.cs, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/GreekAthens_2D.unity
Added a fountain sfx to the water fountain in the Greek Athens 2D level. As the player gets close to the volume increases and decreases as the player moves away from it. If the player is close enough to it a interact prompt will appear. If the player is damaged they can heal else it will say Full Health.
=> Water Fountain & Greek Athens 2D

Mythology Mayhem/Assets/2D Assets/Greek/GreekBoy/GreekBoy/GreekBoy.prefab, Mythology Mayhem/Assets/Global Assets/Audio/SFX/Jump.wav, Mythology Mayhem/Assets/Global Assets/Audio/SFX/Jump.wav.meta, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/GreekLibrary_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekLabyrinth_3D.unity, Mythology Mayhem/Assets/Global Assets/Scripts/HealingPotion.cs, Mythology Mayhem/Assets/Global Assets/Scripts/NewHeartPickup.cs
Changed the jump sfx.
Fixed a bug with the 3d health potions and hearts
=> Jump and Bug fixes

Mythology Mayhem/Assets/2D Assets/Global/Scripts/2D/PlayerStats.cs, Mythology Mayhem/Assets/2D Assets/Greek/GreekBoy/GreekBoy/GreekBoy.prefab, Mythology Mayhem/Assets/3D Assets/Global/Player 3D/Tobias_3D.prefab, Mythology Mayhem/Assets/Global Assets/Scripts/Enemy/Mouse2D.cs, Mythology Mayhem/Assets/Global Assets/Scripts/FPSHealth.cs
2D and 3D Tobias have hurt and die SFXs.
The 2D mouse no longer ignores the player after the player leaves its trigger.
=> Tobias & Mouse2D

Mythology Mayhem/Assets/3D Assets/Global/Scripts/ThreeDLever.cs, Mythology Mayhem/Assets/Global Assets/Art/ButtonsLevers_props/Lever_3/Prefab/Lever_3.prefab, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/3D_Lever_Down.anim, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/3D_Lever_Down.anim.meta, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/3D_Lever_Up.anim, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/3D_Lever_Up.anim.meta, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/Bone_001.controller, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/Bone_001.controller.meta
The 3D levers will now animate up and down.
When down its door is unlocked.
When up its door is locked.
=> 3D Lever Animations

Mythology Mayhem/Assets/3D Assets/Global/Scroll3D.prefab, Mythology Mayhem/Assets/Global Assets/Audio/SFX/Map open 1.wav, Mythology Mayhem/Assets/Global Assets/Audio/SFX/Map open 1.wav.meta, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/GreekAthens_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/GreekLibrary_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Labyrinth_Scenes/GreekLabyrinth_2D_Levers.unity, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekLabyrinth_3D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekLibrary_3D.unity, Mythology Mayhem/Assets/Global Assets/Scripts/ScrollPopup.cs, Mythology Mayhem/Assets/Global Assets/Scripts/ScrollScript.cs, Mythology Mayhem/Assets/Global Assets/UI/Scroll.prefab
3D scrolls now play an SFX when opened.
2D and 3D scrolls have a new SFX.
=> Scroll SFX

Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D_Levers.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D_Statues.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Labyrinth_Scenes/GreekLabyrinth_2D_Levers.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Labyrinth_Scenes/GreekLabyrinth_2D_Pedastals.unity, Mythology Mayhem/Assets/TorchSFXManager.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/GameManager.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/LocalGameManager.cs
Added 2D lighting to all 2D Greek Cavern scenes.
=> Cavern Lights

Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D_Levers.unity, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D_Statues.unity
Foreground sprites now render Infront of the player. Cave doors are now bigger.
=> 2D Cave Sprites

Mythology Mayhem/Assets/2D Assets/Greek/Fountain.prefab, Mythology Mayhem/Assets/2D Assets/Greek/FountainScript.cs, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/GreekAthens_2D.unity
Fixed a bug where the fountain interact UI would not disappear. Added a heal SFX to the fountain. This SFX now plays when the player interacts with the fountain and is healed.
=> Athens Fountain

Mythology Mayhem/Assets/Global Assets/Scenes/Menus/MainMenu.unity, Mythology Mayhem/Assets/Global Assets/Scripts/UI/UI/Menus/MenuManager.cs, Mythology Mayhem/Assets/Global Assets/Scripts/UI/UI/Menus/optionsMenu.cs, Mythology Mayhem/Assets/MainMenuController.cs
Volume sliders now update properly.
=> Options Volume Sliders

Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/GreekLibrary_2D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/Menus/MainMenu.unity, Mythology Mayhem/Assets/Global Assets/Scripts/ScrollScript.cs, Mythology Mayhem/Assets/Global Assets/Scripts/UI/UI/Menus/MenuManager.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/GameManager.cs
Changed the Help panel to a Controls panel.
Updated the Controls panel to reflect all inputs the player can make.
=> Help Panel

Mythology Mayhem/Assets/3D Assets/Global/Player 3D/Tobias_3D.prefab, Mythology Mayhem/Assets/3D Assets/Global/Scripts/Arrow.cs, Mythology Mayhem/Assets/3D Assets/Global/Scripts/Shoot3D.cs, Mythology Mayhem/Assets/Global Assets/Prefabs/TempPrefabs/ArrowAnalog.prefab, Mythology Mayhem/Assets/Global Assets/Prefabs/TempPrefabs/ArrowAnalog2D.prefab, Mythology Mayhem/Assets/Global Assets/Scripts/Health.cs, Mythology Mayhem/Assets/Global Assets/Scripts/TriggerDetector2D.cs, Mythology Mayhem/Assets/Global Assets/Scripts/TriggerDetector3D.cs
The 3D player can now fire an arrow and deal damage to enemies.
=> 3D Bow and Arrow

Mythology Mayhem/Assets/2D Assets/Global/Player2D_Holder.prefab, Mythology Mayhem/Assets/3D Assets/Global/Player3D_Holder.prefab, Mythology Mayhem/Assets/Global Assets/Art/Owl_Follower/Owl_Controller.controller, Mythology Mayhem/Assets/Global Assets/Prefabs/OwlFollower.prefab, Mythology Mayhem/Assets/Global Assets/Scripts/Companions/Companion.cs, Mythology Mayhem/Assets/Global Assets/Scripts/Companions/CompanionController.cs
Simplified the companion controller and companion scripts. Player can now cycle through acquired companions properly.
=> Companions

Mythology Mayhem/Assets/3D Assets/Global/Scripts/WeaponSwitcher.cs, Mythology Mayhem/Assets/Global Assets/Scenes/Menus/MainMenu.unity, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/GameData.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/SaveData.cs
Improved the switching of weapons and off hand items. Weapons and items no longer become invisible when switching unless the next weapon or item is available.
=> Weapon Switching

Mythology Mayhem/Assets/2D Assets/Global/Player2D_Holder.prefab, Mythology Mayhem/Assets/Global Assets/Scripts/Companions/Companion.cs, Mythology Mayhem/Assets/Global Assets/Scripts/Companions/CompanionController.cs, Mythology Mayhem/Assets/Global Assets/Scripts/playerSpawner.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/GameManager.cs
Improved the companion switching mechanic
=> Companion Switching

Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekLabyrinth_3D.unity, Mythology Mayhem/Assets/TorchSFXManager.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/LocalGameManager.cs
Torch Audio in 3D levels is louder now.
=> Torch Audio

Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekLabyrinth_3D.unity, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekLibrary_3D.unity
GreekLabyrinth_3D and GreekLibrary_3D transition points are no longer visible
=> 3D transition points

Mythology Mayhem/Assets/2D Assets/Global/Scripts/2D/Shoot2D.cs, Mythology Mayhem/Assets/2D Assets/Greek/2DCave/cavern_pillar.png, Mythology Mayhem/Assets/2D Assets/Greek/2DCave/cavern_pillar.png.meta, Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D_Levers.unity
Fixed a bug that allowed the 2D player to attack with the sword and bow at the same time. Fixed a bug with the torches in the GreekCavern_2D_Levers level. Torches no longer flicker. Added a scroll to the GreekCavern_2D_Levers level. Added more columns in GreekCavern_2D_Levers level for the levers to be on.
=> Bug Fixes & GreekCavern_2D_Levers

Mythology Mayhem/Assets/Global Assets/Scenes/2D Scenes/Greek 2D/Cavern Scenes/GreekCavern_2D.unity, Mythology Mayhem/Assets/Global Assets/Scripts/QuizManager.cs, Mythology Mayhem/Assets/Global Assets/UI/QuizPanel.prefab
Replaced the old quiz UI image to match the new scroll image. The quiz UI now opens and closes like the pause menu.
=> Fate Quiz UI

Mythology Mayhem/Assets/Global Assets/Scenes/Menus/MainMenu.unity, Mythology Mayhem/Assets/Global Assets/Scripts/OptionsData.cs, Mythology Mayhem/Assets/Global Assets/Scripts/UI/UI/Menus/MenuManager.cs, Mythology Mayhem/Assets/Global Assets/Scripts/UI/UI/Menus/optionsMenu.cs, Mythology Mayhem/Assets/MainMenuController.cs, Mythology Mayhem/Assets/Travis_TestingFolder_WillOrganizeAfterTesting/TestScripts/GameManager.cs, Mythology Mayhem/ProjectSettings/QualitySettings.asset
Graphics options are now working
=> Options Menu

Mythology Mayhem/Assets/3D Assets/Greek/Enemies/Medusa/Scripts/MedusaControlScript.cs, Mythology Mayhem/Assets/Global Assets/Scenes/3D Scenes/Greek 3D/GreekMedusa_3D.unity
Added a SFX for the door as it is rising.
=> GreekMedusa_3D
